# Generated by Django 3.2.25 on 2024-06-16 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorBidmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contractor', models.CharField(max_length=100)),
                ('property_id', models.IntegerField()),
                ('bid_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contractormodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContractorWeeklyUpdateActionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cost_utilized', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_id', models.IntegerField()),
                ('property_id', models.IntegerField()),
                ('contractor_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UpdateActionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='contractor_images/')),
                ('update_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='contractor.contractorweeklyupdateactionmodel')),
            ],
        ),
    ]
